### PR TITLE
Fix: add missing hash to script-src policy

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
Fix CSP violation reported on browser console for

    div.setAttribute( eventName, "t" );

- so add sha256 of "t" (47mKTaMaEn1L3m5DAz9muidMqw636xxw7EFAK/YnPdg=)

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Bumped rails_admin_aaf_theme to just-released 0.1.4 - this fixes the issues I ran into in the Validator Admin interface - #197.
Successfully tested in my env, works all fine.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes , any chance I could get this merged?  Looks like trivial changes....

Thanks a lot in advance for finding the time to look at this.

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Apologies, had fallen out of my review queue somehow, to many PR!.

**Comment by vladimir-mencl-eresearch** [comment]
No problem, thanks for the quick response now!

**Pull request merged**
