### PR TITLE
Fix logout issues

### PR DESCRIPTION
**Pull request by rcaught**
Use browser session length.

### CODE REVIEW

**Comment by smangelsdorf** [comment]
Default Redis TTL is 1 hour for idle sessions, based on a read of the documentation. Is that what you saw during testing?

**Comment by rcaught** [comment]
In testing, it's deleted almost instantly because the blob is stored, shown and then released.

**Comment by rcaught** [comment]
Closes #141

**Comment by smangelsdorf** [comment]
> In testing, it's deleted almost instantly because the blob is stored, shown and then released.

What about session data during normal app usage? (i.e. not while rendering a login error)

**Comment by rcaught** [comment]
Changing strategy here.

There will be a 90 minute session.  Closing a browser won't clear it, but logging out will now.

**Comment by rcaught** [comment]
Redis key will still expire after 90 minutes.  This forces the Rack cookie to be only session based.

**Pull request merged**
