### PR TITLE
Update Nokogiri and deps due to security vuln

### PR DESCRIPTION
**Pull request by bradleybeddoes**
```
DocumentFragment#path now does proper error-checking to handle
behavior introduced in libxml > 2.9.10. In v1.11.4 and v1.11.5,
calling DocumentFragment#path could result in a segfault.
```

### CODE REVIEW

**Comment by bradleybeddoes** [comment]
```
Finished in 8.34 seconds (files took 5.43 seconds to load)
214 examples, 0 failures
```

**Comment by chrisjones120** [comment]
What was the underlying cause for [`41a8283` (#209)](https://github.com/ausaccessfed/validator-service/pull/209/commits/41a8283552e2f3047f00ebfd48c62d88cd6bd7a2)? The strategy seems to be the same as [manager's buildspec](https://github.com/ausaccessfed/rapid-idp-manager/blob/develop/buildspec.yml) which currently works.

**Review by mikelkew — COMMENTED** [review]
Any reason for using the full path everywhere instead of prepending to your `PATH`?
I agree there's probably no need for `rbenv init -` if we're editing the `PATH` ourselves though.

**Comment by chrisjones120** [comment]
~~https://raw.githubusercontent.com/rbenv/rbenv-installer/master/bin/rbenv-installer~~
https://raw.githubusercontent.com/rbenv/rbenv-installer/main/bin/rbenv-installer

I imagine this will be controversial :joy:

**Comment by bradleybeddoes** [comment]
Yeah, I was screwing around with it, have essentially rolled back and made the smallest change.

**Comment by mikelkew** [comment]
https://github.com/rbenv/rbenv-installer/commit/b4e8f205dc6d47885e574dba23dba855a9f3b512

**Review by mikelkew — APPROVED** [review]

**Pull request merged**
