### PR TITLE
Update dependencies to address vulnerabilities

### PR DESCRIPTION
**Pull request by bradleybeddoes**

### CODE REVIEW

**Comment by bradleybeddoes** [comment]
Superceded by #163

**Comment by vladimir-mencl-eresearch** [comment]
... I guess the above comment meant to point to #166  ?  Commenting to add a link, not to nit-pick...

**Comment by bradleybeddoes** [comment]
No idea what you're talking about @vladimir-mencl-eresearch ;-)

**Comment by vladimir-mencl-eresearch** [comment]
You got me for a few seconds .... :-)

**Pull request closed without merging**
